#include "Item/AO_ItemFuelComponent.h"
#include "AbilitySystemBlueprintLibrary.h"

UAO_ItemFuelComponent::UAO_ItemFuelComponent()
{
	PrimaryComponentTick.bCanEverTick = false;
	SetIsReplicatedByDefault(true);
}

void UAO_ItemFuelComponent::BeginPlay()
{
	Super::BeginPlay();

	AActor* Owner = GetOwner();
	if (!Owner) return;

	// ASC ê°€ì ¸ì˜¤ê¸°
	OwnerASC = UAbilitySystemBlueprintLibrary::GetAbilitySystemComponent(Owner);
	if (!OwnerASC)
	{
		UE_LOG(LogTemp, Warning, TEXT("âš  Owner has no AbilitySystemComponent!"));
		return;
	}

	// AttributeSet ê°€ì ¸ì˜¤ê¸° (const_castë¡œ ì•ˆì „í•˜ê²Œ)
	const UAO_Fuel_AttributeSet* FuelSet = OwnerASC->GetSet<UAO_Fuel_AttributeSet>();
	if (!FuelSet)
	{
		UE_LOG(LogTemp, Warning, TEXT("âš  Owner ASC has no FuelAttributeSet!"));
		return;
	}

	OwnerFuelAttributeSet = const_cast<UAO_Fuel_AttributeSet*>(FuelSet);
}

void UAO_ItemFuelComponent::ApplyFuel()
{
	if (!OwnerFuelAttributeSet || !OwnerASC || !GetOwner()->HasAuthority())
		return;

	// ê¸°ì¡´ ì—°ì‚°: Fuel += AddFuelAmount
	float CurrentFuel = OwnerFuelAttributeSet->Fuel.GetCurrentValue();
	float NewFuel = CurrentFuel + AddFuelAmount;

	OwnerFuelAttributeSet->Fuel.SetCurrentValue(NewFuel);

	// ASCì— ì•Œë¦¬ê¸°
	OwnerASC->ForceReplication();
	UE_LOG(LogTemp, Warning, TEXT("ðŸ”¥ Applied Fuel: %.1f â†’ %.1f"), CurrentFuel, NewFuel);
}
