#include "Item/AO_Sample_Fuel.h"
#include "EngineUtils.h"
#include "AbilitySystemComponent.h"
#include "Train/GAS/AO_AddFuel_GameplayAbility.h"
#include "Train/AO_Train.h"


// Sets default values
AAO_Sample_Fuel::AAO_Sample_Fuel()
{
	PrimaryActorTick.bCanEverTick = false;
	bReplicates = true;

	FuelMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("FuelMesh"));
	SetRootComponent(FuelMesh);

	FuelMesh->SetCollisionProfileName(TEXT("OverlapAll"));
	FuelMesh->SetGenerateOverlapEvents(true);
	FuelMesh->OnComponentBeginOverlap.AddDynamic(this, &AAO_Sample_Fuel::OnOverlap);
}

void AAO_Sample_Fuel::BeginPlay()
{
	Super::BeginPlay();
}

void AAO_Sample_Fuel::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

void AAO_Sample_Fuel::OnOverlap(UPrimitiveComponent* Overlapped, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex,
    bool bFromSweep, const FHitResult& SweepResult)

{
    if (!HasAuthority()) return;
    if (bConsumed) return;
    bConsumed = true;

    UE_LOG(LogTemp, Warning, TEXT("ðŸ”¥ OnOverlap Fired! OtherActor = %s"), *GetNameSafe(OtherActor));

    AAO_Train* Train = TargetTrain;
    if (!Train)
    {
        for (TActorIterator<AAO_Train> It(GetWorld()); It; ++It)
        {
            Train = *It;
            break;
        }
    }
    if (!Train) return;

    UAbilitySystemComponent* ASC = Train->GetAbilitySystemComponent();
    if (!ASC)
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ Train ASC is null"));
        return;
    }

    // 1) ì‹œë„: íŠ¸ë ˆì¸ì— ì—ë””í„°ì—ì„œ ì§€ì •í•œ AddEnergyAbilityClassê°€ ìžˆë‹¤ë©´ ê·¸ê±¸ë¡œ ë¨¼ì € ì°¾ëŠ”ë‹¤
    FGameplayAbilitySpec* FoundSpec = nullptr;
    if (Train->AddEnergyAbilityClass)
    {
        FoundSpec = ASC->FindAbilitySpecFromClass(Train->AddEnergyAbilityClass);
    }

    // 2) ëª» ì°¾ì•˜ìœ¼ë©´, ëª¨ë“  AbilitySpecì„ ìˆœíšŒí•˜ë©´ì„œ ë² ì´ìŠ¤ í´ëž˜ìŠ¤ì˜ íŒŒìƒ ì—¬ë¶€ë¡œ ì°¾ê¸°
    if (!FoundSpec)
    {
        for (FGameplayAbilitySpec& Spec : ASC->GetActivatableAbilities()) // ì—”ì§„ ë²„ì „ì— ë”°ë¼ ì ‘ê·¼ìžëª… ë‹¤ë¥¼ ìˆ˜ ìžˆìŒ
        {
            if (Spec.Ability && Spec.Ability->GetClass()->IsChildOf(UAO_AddFuel_GameplayAbility::StaticClass()))
            {
                FoundSpec = &Spec;
                break;
            }
        }
    }

    if (!FoundSpec)
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ Train doesn't have AddEnergy ability (after thorough search)"));
        return;
    }

    // 3) Primary instance (ì¸ìŠ¤í„´ì‹± ì •ì±…ì— ë”°ë¼ nullì¼ ìˆ˜ ìžˆìŒ)
    UAO_AddFuel_GameplayAbility* AbilityInst = nullptr;
    if (FoundSpec->GetPrimaryInstance()) // ì•ˆì „í•˜ê²Œ ê²€ì‚¬
    {
        AbilityInst = Cast<UAO_AddFuel_GameplayAbility>(FoundSpec->GetPrimaryInstance());
    }

    // ì¸ìŠ¤í„´ìŠ¤ê°€ ì—†ë‹¤ë©´(ì˜ˆ: non-instanced), PendingAmountì„ Abilityì— ì§ì ‘ ì“°ëŠ” ë°©ì‹ì€ ë¶ˆê°€ëŠ¥.
    // ê·¸ ê²½ìš° SetByCallerë¥¼ ì‚¬ìš©í•˜ê±°ë‚˜ ìŠ¤íŽ™ì— ì§ì ‘ ê°’ì„ ì£¼ìž…í•´ì•¼ í•¨.
    if (AbilityInst)
    {
        AbilityInst->PendingAmount = AddFuelAmount;
        UE_LOG(LogTemp, Warning, TEXT("âœ… Item: PendingAmount set to ability instance = %f"), AddFuelAmount);
    }
    /*else
    {
        UE_LOG(LogTemp, Warning, TEXT("âš ï¸ Ability instance not available. Will try to apply via Spec SetByCaller fallback."));

        // Fallback: Make a GE Spec directly and SetByCaller; ì´ ë°©ì‹ì€ ability ì¸ìŠ¤í„´ìŠ¤ ì—†ì´ë„ ë™ìž‘
        FGameplayEffectSpecHandle SpecHandle = ASC->MakeOutgoingSpec(UGAS_Effect_AddEnergy::StaticClass(), 1.f, ASC->MakeEffectContext());
        if (SpecHandle.IsValid() && SpecHandle.Data.IsValid())
        {
            FGameplayTag AmountTag = FGameplayTag::RequestGameplayTag(FName("Data.EnergyAmount"));
            SpecHandle.Data->SetSetByCallerMagnitude(AmountTag, AddFuelAmount);
            ASC->ApplyGameplayEffectSpecToSelf(*SpecHandle.Data.Get());
            UE_LOG(LogTemp, Warning, TEXT("âœ… Applied direct GE Spec with SetByCaller amount = %f"), AddFuelAmount);
        }
    }*/

    // 4) Ability í™œì„±í™” (ê°€ëŠ¥í•˜ë©´ Spec->Handle ì‚¬ìš©)
    if (FoundSpec)
    {
        ASC->TryActivateAbility(FoundSpec->Handle);
    }

    Destroy();
}